- name: Install EPEL yum repository
  yum: name=epel-release state=present

- name: Install basic packages for work
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - sysstat
    - iotop
    - atop
    - htop
    - dstat
    - strace
    - perf
    - vim
    - screen
    - telnet
    - curl
    - wget
    - bind-utils
    - net-tools
    - lsof
    - mc
    - lvm2
    - zip
    - unzip
    - tcpdump
    - dos2unix
    - mlocate
    - gcc
    - git
    - nfs-utils
    - xinetd
    - iptables-services
