---
- name: Make directory for Java /opt/java/
  file:
    path: /opt/java/
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"

- name: Download Java7 tarball from Artifactory
  get_url:
    url="{{ java7_download_url }}"
    dest=/opt/java/
  register: java_tar

- name: Unarchive Java7
  unarchive:
    src: /opt/java/{{ java_tar.dest | basename }}
    dest: /opt/java/
    owner: root
    group: root
    remote_src: yes
    list_files: yes
  register: tar_dirname

- name: Create Java7 home symlink
  file: src=/opt/java/{{ tar_dirname.files[0] | dirname}} dest=/opt/java/java7 state=link

- name: Delete Java7 tarball
  file: state=absent path=/opt/java/{{ java_tar.dest | basename }}

- name: Make Java7 available for system with alternatives. Will be default
  alternatives:
    name=java
    link=/usr/bin/java
    path=/opt/java/java7/jre/bin/java
